frr version 10.5.1
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 ip address 192.168.1.1/24
 ip ospf cost 10
 ip ospf network point-to-point
!
interface eth2
 ip address 192.168.2.1/24
 ip ospf cost 30
 ip ospf network point-to-point
!
interface eth3
 ip address 192.168.11.1/24
 ip ospf passive
!
interface lo
 ip address 10.10.10.1/32
!
router ospf
 ospf router-id 10.10.10.1
 network 10.10.10.1/32 area 0.0.0.0
 network 192.168.1.0/24 area 0.0.0.0
 network 192.168.2.0/24 area 0.0.0.0
 network 192.168.11.0/24 area 0.0.0.0
!
line vty
!
